# translations_tk.py

TRANSLATIONS = {
    "en": {
        "window_title": "Pcsx2 Pnach Tool (Tkinter)",
        "cheat_codes_label": "Cheat Codes:", # Corresponds to the single input field
        "pnach_output_label": "PNACH Output:",
        "convert_button": "Convert to PNACH",
        "save_as_button": "Save As...",
        "file_saved_success": "File saved successfully!", # Generic success message
        "file_menu": "File",
        "options_menu": "Options",
        "language_menu": "Language",
        "help_menu": "Help",
        "exit_action": "Exit",
        "system_language_action": "System Language",
        "french_action": "French",
        "english_action": "English",
        "about_action": "About",
        "about_dialog_title": "About Pcsx2 Pnach Tool",
        "about_dialog_text": "Pcsx2 Pnach Tool (Tkinter version)\\nConverts codes to PNACH format.",
        "clear_button": "Clear Fields",
        "no_input_warning_title": "No Input",
        "no_input_warning_text": "Please enter RAW codes.", # Adjusted for single input
        "conversion_success_title": "Conversion Successful",
        "conversion_success_text": "Codes converted to PNACH format.",
        "no_valid_code_warning_title": "No Valid Codes",
        "no_valid_code_warning_text": "No valid codes found to convert.",
        "no_valid_code_with_desc_text": "No valid codes found. Last description: {description}",
        "no_code_to_export_warning_title": "Nothing to Export",
        "no_code_to_export_warning_text": "There is no PNACH data to export.",
        "game_name_input_dialog_title": "Game Name",
        "game_name_input_dialog_label": "Enter the game title:",
        "export_cancelled_title": "Export Cancelled",
        "export_cancelled_no_name_text": "Export cancelled: No game name provided.",
        "game_crc_input_dialog_title": "Game CRC",
        "game_crc_input_dialog_label": "Enter the 8-digit hexadecimal CRC of the game (e.g., A1B2C3D4):", # Clarified
        "export_cancelled_no_crc_text": "Export cancelled: No game CRC provided.",
        "invalid_crc_error_title": "Invalid CRC",
        "invalid_crc_error_text": "The CRC provided is invalid. It should be 8 hexadecimal characters.",
        "save_pnach_dialog_title": "Save PNACH file",
        "pnach_file_filter": "PNACH files (*.pnach);;All files (*.*)", # Original filter string
        "all_files_filter_tk": "All files (*.*)", # Specific for Tkinter file dialog
        "file_saved_success_title": "File Saved",
        "file_saved_success_text_tk": "File saved successfully to: {filepath}", # For formatted message
        "save_error_title": "Save Error",
        "save_error_text": "Could not save file: {error}",
        "gametitle_default": "My Game Title",
        "comment_default": "PNACH codes generated by Pcsx2 Pnach Tool"
    },
    "fr": {
        "window_title": "Pcsx2 Pnach Tool (Tkinter)",
        "cheat_codes_label": "Codes de Triche :", # Corresponds to the single input field
        "pnach_output_label": "Sortie PNACH :",
        "convert_button": "Convertir en PNACH",
        "save_as_button": "Enregistrer sous...",
        "file_saved_success": "Fichier enregistré avec succès !", # Generic success message
        "file_menu": "Fichier",
        "options_menu": "Options",
        "language_menu": "Langue",
        "help_menu": "Aide",
        "exit_action": "Quitter",
        "system_language_action": "Langue du système",
        "french_action": "Français",
        "english_action": "Anglais", # Corrected from "English" to "Anglais" for consistency
        "about_action": "À propos",
        "about_dialog_title": "À propos de Pcsx2 Pnach Tool",
        "about_dialog_text": "Pcsx2 Pnach Tool (version Tkinter)\\nConvertit les codes au format PNACH.",
        "clear_button": "Effacer les champs",
        "no_input_warning_title": "Aucune entrée",
        "no_input_warning_text": "Veuillez entrer des codes RAW.", # Adjusted for single input
        "conversion_success_title": "Conversion réussie",
        "conversion_success_text": "Codes convertis au format PNACH.",
        "no_valid_code_warning_title": "Aucun code valide",
        "no_valid_code_warning_text": "Aucun code valide trouvé à convertir.",
        "no_valid_code_with_desc_text": "Aucun code valide trouvé. Dernière description : {description}",
        "no_code_to_export_warning_title": "Rien à exporter",
        "no_code_to_export_warning_text": "Il n'y a aucune donnée PNACH à exporter.",
        "game_name_input_dialog_title": "Nom du jeu",
        "game_name_input_dialog_label": "Entrez le titre du jeu :",
        "export_cancelled_title": "Exportation annulée",
        "export_cancelled_no_name_text": "Exportation annulée : Aucun nom de jeu fourni.",
        "game_crc_input_dialog_title": "CRC du jeu",
        "game_crc_input_dialog_label": "Entrez le CRC hexadécimal à 8 chiffres du jeu (ex: A1B2C3D4) :", # Clarified
        "export_cancelled_no_crc_text": "Exportation annulée : Aucun CRC de jeu fourni.",
        "invalid_crc_error_title": "CRC invalide",
        "invalid_crc_error_text": "Le CRC fourni est invalide. Il doit comporter 8 caractères hexadécimaux.",
        "save_pnach_dialog_title": "Enregistrer le fichier PNACH",
        "pnach_file_filter": "Fichiers PNACH (*.pnach);;Tous les fichiers (*.*)", # Original filter string
        "all_files_filter_tk": "Tous les fichiers (*.*)", # Specific for Tkinter file dialog
        "file_saved_success_title": "Fichier enregistré",
        "file_saved_success_text_tk": "Fichier enregistré avec succès : {filepath}", # For formatted message
        "save_error_title": "Erreur d'enregistrement",
        "save_error_text": "Impossible d'enregistrer le fichier : {error}",
        "gametitle_default": "Mon Titre De Jeu",
        "comment_default": "Codes PNACH générés par Pcsx2 Pnach Tool"
    }
}

# Langue actuelle (sera définie par l'application au démarrage)
CURRENT_LANG = "en" 

def get_text(key, **kwargs): # Ajout de **kwargs pour permettre le formatage
    text = TRANSLATIONS.get(CURRENT_LANG, TRANSLATIONS["en"]).get(key, key)
    if kwargs:
        try:
            return text.format(**kwargs)
        except KeyError: # Au cas où un placeholder serait manquant dans la traduction
            return text 
    return text
